apiVersion: v1
kind: DeploymentConfig
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mq
  name: mq
spec:
  replicas: 1
  selector:
    io.kompose.service: mq
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: mq
    spec:
      containers:
        - env:
            - name: TZ
              value: Europe/Istanbul
          image: ' '
          name: mq
          ports:
            - containerPort: 5672
            - containerPort: 15672
          resources: {}
      restartPolicy: Always
  test: false
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - mq
        from:
          kind: ImageStreamTag
          namespace: spectrum
          name: rabbitmq:management
      type: ImageChange
status:
  availableReplicas: 0
  latestVersion: 0
  observedGeneration: 0
  replicas: 0
  unavailableReplicas: 0
  updatedReplicas: 0
