apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f docker-compose.k8s.converted.yml --out ../../k8s
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: processorvhf
  name: processorvhf
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: processorvhf
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f docker-compose.k8s.converted.yml --out ../../k8s
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: processorvhf
    spec:
      containers:
      - env:
        - name: BAND
          value: VHF
        - name: BROKER_HOST
          value: mq
        - name: BROKER_PORT
          value: "5672"
        - name: BROKER_PROTOCOL
          value: amqp
        - name: TZ
          value: Europe/Istanbul
        image: custom/spectrum/processor
        imagePullPolicy: Never
        name: processorvhf
        ports:
        - containerPort: 9080
        resources: {}
      restartPolicy: Always
status: {}
